### ISSUE TITLE
Having issues installing with devtools::install_github

### ISSUE THREAD

**Issue by welch16** [sjbeckett/localcovid19now#58]
Hello,

Great work with the package. I am reviewing the package for JOSS, and when I am trying to install the package using the `devtools::install_github` instruction, I got the following error:

```
Downloading GitHub repo sjbeckett/localcovid19now@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/sjbeckett/localcovid19now/tarball/HEAD' failed
```

However, if download/clone the repository and use `devtools::install_local` then it is possible to install the package. I suspect that this issue may happen to other users, in which case may be useful to have alternative instructions to install the package

**Comment by sjbeckett** [comment]
Many thanks for reporting this @welch16. I'm glad the `devtools::install_local` method allowed you to install the package.
I'm unable to reproduce this error, and not exactly sure what the underlying cause is. I'm wondering if you could try again and see if you get the same error? and whether you have seen this with other packages that use the `devtools::install_github` approach?

If not, then it is possible that changing timeout options could help: https://github.com/dmcable/spacexr/issues/62
or changing download options could help: https://github.com/facebookincubator/GeoLift/issues/53

**Comment by welch16** [comment]
I tried installing the package again after increasing the timeout and it installed correctly. I wonder if this is a common enough issue to mentioning it in the installation instructions

Thanks for your help
